# Generated by Django 4.1.3 on 2022-11-18 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('example', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExampleSingletonModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_singleton_id', models.IntegerField(default=1, editable=False, help_text='An ID to use for this mixin, in case the model uses some non-standard PK.')),
                ('name', models.CharField(max_length=128, unique=True)),
            ],
            options={
                'verbose_name': 'Example Singleton',
                'verbose_name_plural': 'Example Singletons',
            },
        ),
    ]
